name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.15', '1.16', '1.17']
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check formatting
        run: |
          if [ -n "$(gofmt -s -l .)" ]; then gofmt -s -d .; exit 1; fi

      - name: Run unit tests
        run: go test .
